version: '3'
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_INITDB_DATABASE=femida
    env_file:
      - secret
    volumes:
      - ./docker/data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles

  frontend:
    build:
      context: frontend
    env_file:
      - frontend/envfile
      - secret
    depends_on:
      - mongodb
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/media/:/media/
      - ./docker/ssl:/etc/nginx/ssl
