version: 2
jobs:
  build:
    steps:
      # `deploy` step: identical to a `run` step, but uses only one container:
      # https://circleci.com/docs/2.0/configuration-reference/#deploy 
      - deploy:
          name: deploy to femida
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              ssh circleci@femida.emsch.ru "cd /femida && git pull && docker-compose up --build -d"
            else
              echo "Not master branch, dry run only"
            fi
